version: 2.1
jobs:
 build:
   executor: python/default
   steps:
      - checkout
      - setup_remote_docker
      - run: pip install pipenv
      - run:
          command: |
            cd keview-api
            pipenv install --dev --skip-lock
          name: Keview-API
      - run:
          command: |
            cd keview-api
            pipenv run flake8
          name: Lint Test
      - run:
          command: |
            cd keview-api
            export KEVIEW_HOST=api
            make test
orbs:
  python: circleci/python@0.3.2
  docker: circleci/docker@1.4.0