version: 2.1
jobs:
 build:
   executor: python/default
   steps:
      - checkout
      - run: pip install pipenv
      - run:
          command: |
            cd keview-api
            pipenv install --dev --skip-lock
          name: Keview-API
      - run:
          command: |
            cd keview-api
            pipenv run flake8
          name: Lint Test
orbs:
  python: circleci/python@0.3.2