version: 2.1
jobs:
 build:
   executor: python/default
   steps:
      - checkout
      - python/load-cache
      - run: pip install pipenv
      - python/save-cache
      - run:
          command: |
            cd keview-api
            pipenv install --dev --skip-lock
            pipenv run flake8
            # # pytest would be a dep in requirements.txt
            # pytest
          name: Keview-API
orbs:
  python: circleci/python@0.3.2